### ISSUE TITLE
Añadir un calendario que Enseñe todo los eventos

### ISSUE THREAD

**Issue by aallfredo** [aallfredo/ArrancaPr#12]
Podemos usar color coding basado en donde va a ser.

**Comment by emartinez06** [comment]
Se puede usar Google Calendar. Ya tengo uno hecho. Se agrega a la página y listo.

**Comment by aallfredo** [comment]
Aqui lo tienes abrete un pull y ponlo en algun sitio que haga sentido en la pagina.

<iframe src="https://calendar.google.com/calendar/embed?src=arrancaprcorp%40gmail.com&ctz=America/New_York" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

**Comment by aallfredo** [comment]
`<iframe src="https://calendar.google.com/calendar/embed?src=arrancaprcorp%40gmail.com&ctz=America/New_York" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>`

**Comment by emartinez06** [comment]
Ya subi el fix. Verificar.

**Comment by aallfredo** [comment]
Merged and closed. Gracias!

**Comment by aallfredo** [comment]
@emartinez-dat sale hoy.
