### ISSUE TITLE
New Calendar page needs to follow formating from the other pages

### ISSUE THREAD

**Issue by aallfredo** [aallfredo/ArrancaPr#18]
The header is not the same style and is not centered.

**Comment by emartinez06** [comment]
Trabajare con esto

**Comment by aallfredo** [comment]
@emartinez-dat tranquilo i got it estoy bregando en tickets hoy dejame ver lo que acabo y el resto despues vemos que importa.

**Comment by aallfredo** [comment]
@emartinez-dat gracias esta en prod
